name: CI

on:
  push:
    branches: [ "master", "test-ci" ]
  workflow_dispatch:

env:
  BUILD_TYPE: MinSizeRel
  EMSDK: ${{github.workspace}}/emsdk
  VCPKG_ROOT: ${{github.workspace}}/vcpkg

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Tools
        run: sudo apt-get update && sudo apt-get install -y build-essential curl zip unzip tar gdb cmake git python3 ninja-build pkg-config

      - name: Install Emscripten
        run: |
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk && ./emsdk install latest && ./emsdk activate latest
        
      - name: Install vcpkg
        run: |
          git clone https://github.com/Microsoft/vcpkg.git
          cd vcpkg && ./bootstrap-vcpkg.sh

      - name: Build
        run: |
          cmake --preset emscripten-min-release .
          cd build
          ninja
          cd ..
          cp build/noiz2sa.* web/

      - uses: actions/upload-pages-artifact@v1
        with:
          path: ${{github.workspace}}/web

  deploy:
    needs: build
    permissions:
      id-token: write
      pages: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/deploy-pages@v2
        id: deployment
